spring:
  application:
    name: tickets-service

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost:3306}/arqui?useSSL=true&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

server:
  port: 0
  servlet:
    context-path: /

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_CLIENT:localhost:8761}/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include: mappings

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
    path: /tickets-service/v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    url: /tickets-service/v3/api-docs
    config-url: /tickets-service/v3/api-docs/swagger-config
    urls:
      - url:
