spring:
  application:
    name: reservations-service

  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost:3306}/eventra?useSSL=true&allowPublicKeyRetrieval=true
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

server:
  port: 0
  servlet:
    context-path: /

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_CLIENT:localhost:8761}/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  level:
    root: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, mappings

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
    path: /reservations-service/v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    url: /reservations-service/v3/api-docs
    config-url: /reservations-service/v3/api-docs/swagger-config
    urls:
      - url: /reservations-service/v3/api-docs
        name: reservations-service
        display-name: reservations-service

openapi:
  service:
    title: reservations-service doc
    version: 1.0.0
    url: http://${URL_SERVICE:localhost}:8080
