spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost:3306}/arqui?useSSL=true&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

server:
  port: 0
  servlet:
    context-path: /

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_CLIENT:localhost:8761}/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  level:
    root: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: mappings

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
    path: /payment-service/v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    url: /payment-service/v3/api-docs
    config-url: /payment-service/v3/api-docs/swagger-config
    urls:
      - url: /payment-service/v3/api-docs
        name: payment-service
        display-name: payment-service

openapi:
  service:
    title: payment-service doc
    version: 1.0.0
    url: http://${URL_SERVICE:localhost}:8080
